/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import ChevronLeftIcon from '@mui/icons-material/ChevronLeft';
import { SvgIcon, Button } from '@mui/material';
import { styled } from '@mui/material/styles';

const AvailabilityV21 = styled('div')({
  backgroundColor: `rgba(186, 186, 186, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `844px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const CheckAvailability = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `390px`,
  height: `44px`,
  position: `absolute`,
  left: `0px`,
  top: `17px`,
});

const Frame25 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `8px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `91px`,
  height: `52px`,
  left: `14px`,
  top: `81px`,
  overflow: `hidden`,
});

const Calendar = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro`,
  fontWeight: `400`,
  fontSize: `40px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `52px`,
  height: `52px`,
  position: `absolute`,
  left: `15px`,
  top: `0px`,
});

const Frame61 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `12px`,
  top: `601px`,
});

const Frame57 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `81px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q1000 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `81px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Frame58 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `81px`,
  height: `52px`,
  margin: `0px 0px 0px 12px`,
  overflow: `hidden`,
});

const Q1100 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `81px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Frame59 = styled('div')({
  backgroundColor: `rgba(237, 108, 2, 1)`,
  border: `1px solid rgba(255, 255, 255, 1)`,
  boxSizing: `border-box`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `81px`,
  height: `52px`,
  margin: `0px 0px 0px 12px`,
  overflow: `hidden`,
});

const Q1200 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `81px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Frame60 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `81px`,
  height: `52px`,
  margin: `0px 0px 0px 12px`,
  overflow: `hidden`,
});

const Q100 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `81px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Frame62 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `12px`,
  top: `663px`,
});

const Frame571 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `81px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q200 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `81px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Frame581 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `81px`,
  height: `52px`,
  margin: `0px 0px 0px 12px`,
  overflow: `hidden`,
});

const Q300 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `81px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Frame591 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `81px`,
  height: `52px`,
  margin: `0px 0px 0px 12px`,
  overflow: `hidden`,
});

const Q400 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `81px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Frame601 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `81px`,
  height: `52px`,
  margin: `0px 0px 0px 12px`,
  overflow: `hidden`,
});

const Q500 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `81px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Frame56 = styled('div')({
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `0px 8px 8px 0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `275px`,
  left: `92px`,
  top: `81px`,
  overflow: `hidden`,
});

const Frame26 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q1 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame27 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q2 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame28 = styled('div')({
  backgroundColor: `rgba(237, 108, 2, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q3 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame29 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q4 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame30 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q5 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame31 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q6 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame32 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q7 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame33 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q8 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame34 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q9 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame35 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q10 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame36 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q11 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame37 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q12 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame38 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q13 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame39 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q14 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame40 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q15 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame41 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q16 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame42 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q17 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame43 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q18 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame44 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q19 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame45 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q20 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame46 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q21 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame47 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q22 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame48 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q23 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame49 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q24 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame50 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q25 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame51 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q26 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame52 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q27 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame53 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q28 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame54 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q29 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame55 = styled('div')({
  backgroundColor: `rgba(164, 164, 164, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `55px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Q30 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Button1 = styled(Button)(({ theme }) => ({
  width: `346px`,
  height: `60px`,
  position: `absolute`,
  left: `21px`,
  top: `756px`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `15px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
}));

const Frame63 = styled('div')({
  backgroundColor: `rgba(221, 221, 221, 1)`,
  borderRadius: `8px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `353px`,
  height: `401px`,
  left: `15px`,
  top: `171px`,
  overflow: `hidden`,
});

const AvailableOptions = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Rounded`,
  fontWeight: `500`,
  fontSize: `20px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
  width: `287px`,
  height: `38px`,
  position: `absolute`,
  left: `7px`,
  top: `233px`,
});

const Q1AdultX8181Us = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `349px`,
  height: `38px`,
  position: `absolute`,
  left: `18px`,
  top: `314px`,
}));

const NumberOfTravelers = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Rounded`,
  fontWeight: `500`,
  fontSize: `20px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
  width: `287px`,
  height: `38px`,
  position: `absolute`,
  left: `7px`,
  top: `-2px`,
});

const YouCanSelectUpToTrav = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `349px`,
  height: `38px`,
  position: `absolute`,
  left: `7px`,
  top: `36px`,
}));

const AdultAges15Span1 = styled('span')(({ theme }) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Rounded`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
}));

const AdultAges15Span2 = styled('span')(({ theme }) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Rounded`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
}));

const AdultAges15 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: 'unset',
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
  width: `201px`,
  height: `33px`,
  position: `absolute`,
  left: `18px`,
  top: `98px`,
}));

const WithEnglishGuide = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Rounded`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
  width: `201px`,
  height: `33px`,
  position: `absolute`,
  left: `18px`,
  top: `281px`,
}));

const Q8181Us = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Rounded`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
  width: `201px`,
  height: `33px`,
  position: `absolute`,
  left: `18px`,
  top: `352px`,
}));

const ChildAges314Span1 = styled('span')(({ theme }) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Rounded`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
}));

const ChildAges314Span2 = styled('span')(({ theme }) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Rounded`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
}));

const ChildAges314 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: 'unset',
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
  width: `201px`,
  height: `33px`,
  position: `absolute`,
  left: `18px`,
  top: `169px`,
}));

const Q110 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `32px`,
  height: `29px`,
  position: `absolute`,
  left: `269px`,
  top: `102px`,
});

const Q0 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `32px`,
  height: `29px`,
  position: `absolute`,
  left: `269px`,
  top: `170px`,
});

const PlusCircle = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `312px`,
  top: `102px`,
});

const PlusCircle1 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `312px`,
  top: `170px`,
});

const MinusCircle = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `229px`,
  top: `102px`,
});

const MinusCircle1 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(164, 164, 164, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `229px`,
  top: `170px`,
});

function AvailabilityV2(props) {
  return (
    <AvailabilityV21 className={props.className}>
      <SvgIcon
        component={ChevronLeftIcon}
        htmlColor={`rgba(0, 0, 0, 1)`}
      ></SvgIcon>
      <CheckAvailability>{`Check Availability`}</CheckAvailability>
      <Frame25>
        <Calendar>{`􀉉`}</Calendar>
      </Frame25>
      <Frame61>
        <Frame57>
          <Q1000>{`10:00`}</Q1000>
        </Frame57>
        <Frame58>
          <Q1100>{`11:00`}</Q1100>
        </Frame58>
        <Frame59>
          <Q1200>{`12:00`}</Q1200>
        </Frame59>
        <Frame60>
          <Q100>{`1:00`}</Q100>
        </Frame60>
      </Frame61>
      <Frame62>
        <Frame571>
          <Q200>{`2:00`}</Q200>
        </Frame571>
        <Frame581>
          <Q300>{`3:00`}</Q300>
        </Frame581>
        <Frame591>
          <Q400>{`4:00`}</Q400>
        </Frame591>
        <Frame601>
          <Q500>{`5:00`}</Q500>
        </Frame601>
      </Frame62>
      <Frame56>
        <Frame26>
          <Q1>{`1`}</Q1>
        </Frame26>
        <Frame27>
          <Q2>{`2`}</Q2>
        </Frame27>
        <Frame28>
          <Q3>{`3`}</Q3>
        </Frame28>
        <Frame29>
          <Q4>{`4`}</Q4>
        </Frame29>
        <Frame30>
          <Q5>{`5`}</Q5>
        </Frame30>
        <Frame31>
          <Q6>{`6`}</Q6>
        </Frame31>
        <Frame32>
          <Q7>{`7`}</Q7>
        </Frame32>
        <Frame33>
          <Q8>{`8`}</Q8>
        </Frame33>
        <Frame34>
          <Q9>{`9`}</Q9>
        </Frame34>
        <Frame35>
          <Q10>{`10`}</Q10>
        </Frame35>
        <Frame36>
          <Q11>{`11`}</Q11>
        </Frame36>
        <Frame37>
          <Q12>{`12`}</Q12>
        </Frame37>
        <Frame38>
          <Q13>{`13`}</Q13>
        </Frame38>
        <Frame39>
          <Q14>{`14`}</Q14>
        </Frame39>
        <Frame40>
          <Q15>{`15`}</Q15>
        </Frame40>
        <Frame41>
          <Q16>{`16`}</Q16>
        </Frame41>
        <Frame42>
          <Q17>{`17`}</Q17>
        </Frame42>
        <Frame43>
          <Q18>{`18`}</Q18>
        </Frame43>
        <Frame44>
          <Q19>{`19`}</Q19>
        </Frame44>
        <Frame45>
          <Q20>{`20`}</Q20>
        </Frame45>
        <Frame46>
          <Q21>{`21`}</Q21>
        </Frame46>
        <Frame47>
          <Q22>{`22`}</Q22>
        </Frame47>
        <Frame48>
          <Q23>{`23`}</Q23>
        </Frame48>
        <Frame49>
          <Q24>{`24`}</Q24>
        </Frame49>
        <Frame50>
          <Q25>{`25`}</Q25>
        </Frame50>
        <Frame51>
          <Q26>{`26`}</Q26>
        </Frame51>
        <Frame52>
          <Q27>{`27`}</Q27>
        </Frame52>
        <Frame53>
          <Q28>{`28`}</Q28>
        </Frame53>
        <Frame54>
          <Q29>{`29`}</Q29>
        </Frame54>
        <Frame55>
          <Q30>{`30`}</Q30>
        </Frame55>
      </Frame56>
      <Button1
        size={'large'}
        color={'warning'}
        disabled={false}
        variant={'contained'}
      >
        {'Book'}
      </Button1>
      <Frame63>
        <AvailableOptions>{`Available Options`}</AvailableOptions>
        <Q1AdultX8181Us>{`1 Adult x 81,81 US$`}</Q1AdultX8181Us>
        <NumberOfTravelers>{`Number of travelers`}</NumberOfTravelers>
        <YouCanSelectUpToTrav>
          {`You can select up to # travelers in total.`}
        </YouCanSelectUpToTrav>
        <AdultAges15>
          <AdultAges15Span1>{`Adult (Ages 15-`}</AdultAges15Span1>
          <AdultAges15Span2>{`􀯠)`}</AdultAges15Span2>
        </AdultAges15>
        <WithEnglishGuide>{`With English Guide`}</WithEnglishGuide>
        <Q8181Us>{`81,81 US$`}</Q8181Us>
        <ChildAges314>
          <ChildAges314Span1>{`Child (Ages 3-14`}</ChildAges314Span1>
          <ChildAges314Span2>{`)`}</ChildAges314Span2>
        </ChildAges314>
        <Q110>{`1`}</Q110>
        <Q0>{`0`}</Q0>
        <PlusCircle>{`􀁌`}</PlusCircle>
        <PlusCircle1>{`􀁌`}</PlusCircle1>
        <MinusCircle>{`􀁎`}</MinusCircle>
        <MinusCircle1>{`􀁎`}</MinusCircle1>
      </Frame63>
    </AvailabilityV21>
  );
}

export default AvailabilityV2;
