/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import ChevronLeftIcon from '@mui/icons-material/ChevronLeft';
import { SvgIcon, Button } from '@mui/material';
import Image4Image from '../../Downloads/HotelActivitiesBoatT1/src/assets/images/HotelactivitiesBoatTourExpanded_image_4.png';
import { styled } from '@mui/material/styles';
import Image7Image from '../../Downloads/HotelActivitiesBoatT1/src/assets/images/HotelactivitiesBoatTourExpanded_image_7.png';
import Image8Image from '../../Downloads/HotelActivitiesBoatT1/src/assets/images/HotelactivitiesBoatTourExpanded_image_8.png';
import Image9Image from '../../Downloads/HotelActivitiesBoatT1/src/assets/images/HotelactivitiesBoatTourExpanded_image_9.png';
import Image10Image from '../../Downloads/HotelActivitiesBoatT1/src/assets/images/HotelactivitiesBoatTourExpanded_image_10.png';

const HotelActivitiesBoatT = styled('div')({
  backgroundColor: `rgba(186, 186, 186, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1176px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Prague = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Rounded`,
  fontWeight: `700`,
  fontSize: `40px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
  textShadow: `0px 8px 8px rgba(0, 0, 0, 0.5)`,
  width: `212px`,
  height: `62px`,
  position: `absolute`,
  left: `0px`,
  top: `198px`,
});

const WelcomeTo = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Text`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `140px`,
  height: `30px`,
  position: `absolute`,
  left: `0px`,
  top: `183px`,
});

const Image4 = styled('img')({
  height: `268px`,
  width: `390px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const BestOfPragueBoatTour = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Display`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `316px`,
  height: `49px`,
  position: `absolute`,
  left: `0px`,
  top: `219px`,
}));

const OverView = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Display`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `368px`,
  height: `40px`,
  position: `absolute`,
  left: `21px`,
  top: `667px`,
}));

const Summary = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Display`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `368px`,
  height: `40px`,
  position: `absolute`,
  left: `18px`,
  top: `350px`,
}));

const Frame15 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `390px`,
  height: `58px`,
  left: `0px`,
  top: `707px`,
  overflow: `hidden`,
});

const Q6HoursApprox = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Display`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `316px`,
  height: `58px`,
  position: `absolute`,
  left: `74px`,
  top: `0px`,
});

const Clock = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `29px`,
  height: `37px`,
  position: `absolute`,
  left: `33px`,
  top: `11px`,
});

const Frame16 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `390px`,
  height: `58px`,
  left: `0px`,
  top: `764px`,
  overflow: `hidden`,
});

const NextAvailableTomorro = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Display`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `316px`,
  height: `58px`,
  position: `absolute`,
  left: `74px`,
  top: `0px`,
});

const Calendar = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `30px`,
  height: `37px`,
  position: `absolute`,
  left: `32px`,
  top: `12px`,
});

const Frame17 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `390px`,
  height: `58px`,
  left: `0px`,
  top: `821px`,
  overflow: `hidden`,
});

const InstantConfirmation = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Display`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `316px`,
  height: `58px`,
  position: `absolute`,
  left: `74px`,
  top: `0px`,
});

const CheckmarkSeal = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `31px`,
  height: `37px`,
  position: `absolute`,
  left: `32px`,
  top: `11px`,
});

const Frame18 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `390px`,
  height: `58px`,
  left: `0px`,
  top: `878px`,
  overflow: `hidden`,
});

const EmailTicket = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Display`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `316px`,
  height: `57px`,
  position: `absolute`,
  left: `74px`,
  top: `0px`,
});

const Ticket = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `35px`,
  height: `37px`,
  position: `absolute`,
  left: `30px`,
  top: `10px`,
});

const Frame19 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `390px`,
  height: `57px`,
  left: `0px`,
  top: `935px`,
  overflow: `hidden`,
});

const FreeCancellation = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Display`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `316px`,
  height: `57px`,
  position: `absolute`,
  left: `74px`,
  top: `0px`,
});

const DollarsignArrowCircl = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `31px`,
  height: `37px`,
  position: `absolute`,
  left: `32px`,
  top: `10px`,
});

const Frame20 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `390px`,
  height: `58px`,
  left: `0px`,
  top: `991px`,
  overflow: `hidden`,
});

const GroupSize25 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Display`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `316px`,
  height: `57px`,
  position: `absolute`,
  left: `74px`,
  top: `0px`,
});

const Person3 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `51px`,
  height: `37px`,
  position: `absolute`,
  left: `22px`,
  top: `10px`,
});

const Frame21 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `390px`,
  height: `58px`,
  left: `0px`,
  top: `1048px`,
  overflow: `hidden`,
});

const AvailableInEnglish = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Display`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `316px`,
  height: `57px`,
  position: `absolute`,
  left: `74px`,
  top: `0px`,
});

const Globe = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `51px`,
  height: `37px`,
  position: `absolute`,
  left: `22px`,
  top: `10px`,
});

const Button1 = styled(Button)(({ theme }) => ({
  width: `329px`,
  position: `absolute`,
  left: `32px`,
  top: `1120px`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `15px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
}));

const Frame22 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `10px`,
  top: `277px`,
});

const Image7 = styled('div')({
  backgroundImage: `url(${Image7Image})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  border: `3px solid rgba(0, 0, 0, 0.5)`,
  borderRadius: `20px`,
  width: `84px`,
  height: `56px`,
  margin: `0px`,
});

const Image8 = styled('div')({
  backgroundImage: `url(${Image8Image})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  border: `3px solid rgba(0, 0, 0, 0.5)`,
  borderRadius: `20px`,
  width: `84px`,
  height: `55.84px`,
  margin: `0px 0px 0px 11px`,
});

const Image9 = styled('div')({
  backgroundImage: `url(${Image9Image})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  border: `3px solid rgba(0, 0, 0, 0.5)`,
  borderRadius: `20px`,
  width: `84px`,
  height: `56px`,
  margin: `0px 0px 0px 11px`,
});

const Image10 = styled('div')({
  backgroundImage: `url(${Image10Image})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  border: `3px solid rgba(0, 0, 0, 0.5)`,
  borderRadius: `20px`,
  width: `84px`,
  height: `55.84px`,
  margin: `0px 0px 0px 11px`,
});

const Frame73 = styled('div')({
  backgroundColor: `rgba(221, 221, 221, 1)`,
  borderRadius: `8px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `342px`,
  height: `260px`,
  left: `19px`,
  top: `396px`,
  overflow: `hidden`,
});

const LoremIpsumDolorSitAm = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `315px`,
  height: `204px`,
  position: `absolute`,
  left: `14px`,
  top: `22px`,
});

function HotelActivitiesBoatT1(props) {
  return (
    <HotelActivitiesBoatT className={props.className}>
      <Prague>{`Prague`}</Prague>
      <WelcomeTo>{`Welcome to`}</WelcomeTo>
      <Image4 src={Image4Image} loading="lazy" alt={'image 4'} />
      <SvgIcon
        component={ChevronLeftIcon}
        htmlColor={`rgba(0, 0, 0, 1)`}
      ></SvgIcon>
      <BestOfPragueBoatTour>
        {`Best of Prague - Boat Tours`}
      </BestOfPragueBoatTour>
      <OverView>{`OverView`}</OverView>
      <Summary>{`Summary`}</Summary>
      <Frame15>
        <Q6HoursApprox>{`6 Hours (approx.)`}</Q6HoursApprox>
        <Clock>{`􀐫`}</Clock>
      </Frame15>
      <Frame16>
        <NextAvailableTomorro>
          {`Next Available: Tomorrow`}
        </NextAvailableTomorro>
        <Calendar>{`􀉉`}</Calendar>
      </Frame16>
      <Frame17>
        <InstantConfirmation>{`Instant Confirmation`}</InstantConfirmation>
        <CheckmarkSeal>{`􀇺`}</CheckmarkSeal>
      </Frame17>
      <Frame18>
        <EmailTicket>{`Email Ticket`}</EmailTicket>
        <Ticket>{`􀪃`}</Ticket>
      </Frame18>
      <Frame19>
        <FreeCancellation>{`Free Cancellation`}</FreeCancellation>
        <DollarsignArrowCircl>{`􁎣`}</DollarsignArrowCircl>
      </Frame19>
      <Frame20>
        <GroupSize25>{`Group Size: 25`}</GroupSize25>
        <Person3>{`􀝊`}</Person3>
      </Frame20>
      <Frame21>
        <AvailableInEnglish>{`Available in English`}</AvailableInEnglish>
        <Globe>{`􀆪`}</Globe>
      </Frame21>
      <Button1
        size={'large'}
        color={'warning'}
        disabled={false}
        variant={'contained'}
      >
        {'Check Availability'}
      </Button1>
      <Frame22>
        <Image7></Image7>
        <Image8></Image8>
        <Image9></Image9>
        <Image10></Image10>
      </Frame22>
      <Frame73>
        <LoremIpsumDolorSitAm>
          {`Lorem ipsum dolor sit amet consectetur. Ut convallis ante netus accumsan. At condimentum in nunc ut vitae. Hac tempus aliquam amet diam euismod neque. Orci amet pulvinar tincidunt quis pellentesque ut. Gravida aenean faucibus odio neque sed rhoncus vitae amet. Adipiscing pellentesque neque curabitur neque. Sed quisque vestibulum laoreet pellentesque commodo in. Morbi sem adipiscing at commodo id tristique. Sed nunc sit in lectus urna vitae tincidunt.`}
        </LoremIpsumDolorSitAm>
      </Frame73>
    </HotelActivitiesBoatT>
  );
}

export default HotelActivitiesBoatT1;
