/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import ChevronLeftIcon from '@mui/icons-material/ChevronLeft';
import { SvgIcon } from '@mui/material';
import Image3Image from 'src/assets/images/Hotelactivitiesmain_image_3.png';
import Image4Image from 'src/assets/images/Hotelactivitiesmain_image_4.png';
import Image5Image from 'src/assets/images/Hotelactivitiesmain_image_5.png';
import Image6Image from 'src/assets/images/Hotelactivitiesmain_image_6.png';
import Image41Image from 'src/assets/images/Hotelactivitiesmain_image_4_1.png';
import Image51Image from 'src/assets/images/Hotelactivitiesmain_image_5_1.png';
import Image61Image from 'src/assets/images/Hotelactivitiesmain_image_6_1.png';
import { styled } from '@mui/material/styles';

const HotelActivitiesMain1 = styled('div')({
  backgroundColor: `rgba(186, 186, 186, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1218px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Image3 = styled('img')({
  height: `260px`,
  width: `390px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Prague = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Rounded`,
  fontWeight: `700`,
  fontSize: `40px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
  textShadow: `0px 8px 8px rgba(0, 0, 0, 0.5)`,
  width: `212px`,
  height: `62px`,
  position: `absolute`,
  left: `0px`,
  top: `198px`,
});

const Frame3 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 0.5)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `390px`,
  height: `46px`,
  left: `0px`,
  top: `706px`,
  overflow: `hidden`,
});

const Frame4 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `389px`,
  height: `29.39px`,
  left: `1px`,
  top: `0px`,
});

const Explore = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Rounded`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
  width: `91px`,
  height: `46px`,
  margin: `0px`,
});

const Tours = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Rounded`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
  width: `91px`,
  height: `46px`,
  margin: `0px 0px 0px 5px`,
});

const Tickets = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Rounded`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
  width: `91px`,
  height: `46px`,
  margin: `0px 0px 0px 5px`,
});

const Other = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Rounded`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
  width: `91px`,
  height: `46px`,
  margin: `0px 0px 0px 5px`,
});

const WelcomeTo = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Text`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `140px`,
  height: `30px`,
  position: `absolute`,
  left: `0px`,
  top: `183px`,
});

const Frame74 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `421px`,
  left: `17px`,
  top: `783px`,
  overflow: `hidden`,
});

const Boat = styled('div')({
  backgroundColor: `rgba(231, 231, 231, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `40px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  height: `411px`,
  width: `357px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Image4 = styled('img')({
  height: `268px`,
  width: `357px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const BestOfPragueBoatTour = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `357px`,
  height: `49px`,
  position: `absolute`,
  left: `0px`,
  top: `268px`,
});

const Q8181Us = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `172px`,
  height: `32px`,
  position: `absolute`,
  left: `179px`,
  top: `376px`,
});

const From = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `52px`,
  height: `26px`,
  position: `absolute`,
  left: `27px`,
  top: `373px`,
});

const LoremIpsumDolorSitAm = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `305px`,
  height: `48px`,
  position: `absolute`,
  left: `27px`,
  top: `317px`,
});

const Castle = styled('div')({
  backgroundColor: `rgba(231, 231, 231, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `40px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  height: `411px`,
  width: `357px`,
  margin: `34px 0px 0px 0px`,
  overflow: `hidden`,
});

const Image5 = styled('img')({
  height: `267.75px`,
  width: `357px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const BestOfPragueCastleTo = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `357px`,
  height: `56px`,
  position: `absolute`,
  left: `0px`,
  top: `268px`,
});

const Q8181Us1 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `172px`,
  height: `32px`,
  position: `absolute`,
  left: `179px`,
  top: `369px`,
});

const From1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `52px`,
  height: `26px`,
  position: `absolute`,
  left: `18px`,
  top: `372px`,
});

const LoremIpsumDolorSitAm1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `305px`,
  height: `48px`,
  position: `absolute`,
  left: `26px`,
  top: `317px`,
});

const Food = styled('div')({
  backgroundColor: `rgba(231, 231, 231, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `40px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  height: `411px`,
  width: `357px`,
  margin: `34px 0px 0px 0px`,
  overflow: `hidden`,
});

const Image6 = styled('img')({
  height: `267.75px`,
  width: `357px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const BestOfPragueFoodTour = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `357px`,
  height: `56px`,
  position: `absolute`,
  left: `0px`,
  top: `268px`,
});

const Q8181Us2 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `172px`,
  height: `32px`,
  position: `absolute`,
  left: `179px`,
  top: `366px`,
});

const From2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `52px`,
  height: `26px`,
  position: `absolute`,
  left: `18px`,
  top: `372px`,
});

const LoremIpsumDolorSitAm2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `305px`,
  height: `48px`,
  position: `absolute`,
  left: `25px`,
  top: `317px`,
});

const Frame14 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `357px`,
  height: `364px`,
  left: `12px`,
  top: `321px`,
});

const Boat1 = styled('div')({
  backgroundColor: `rgba(231, 231, 231, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `40px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `301px`,
  height: `364px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Image41 = styled('img')({
  height: `254px`,
  width: `301px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const BestOfPragueBoatTour1 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `301px`,
  height: `49px`,
  position: `absolute`,
  left: `0px`,
  top: `268px`,
});

const Q8181Us3 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `172px`,
  height: `32px`,
  position: `absolute`,
  left: `129px`,
  top: `320px`,
});

const From3 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `52px`,
  height: `26px`,
  position: `absolute`,
  left: `33px`,
  top: `317px`,
});

const Castle1 = styled('div')({
  backgroundColor: `rgba(231, 231, 231, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `40px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `301px`,
  height: `364px`,
  margin: `0px 0px 0px 16px`,
  overflow: `hidden`,
});

const Image51 = styled('img')({
  height: `225.75px`,
  width: `301px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const BestOfPragueCastleTo1 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `301px`,
  height: `56px`,
  position: `absolute`,
  left: `0px`,
  top: `226px`,
});

const Q8181Us4 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `172px`,
  height: `32px`,
  position: `absolute`,
  left: `151px`,
  top: `285px`,
});

const From4 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `52px`,
  height: `26px`,
  position: `absolute`,
  left: `20px`,
  top: `282px`,
});

const Food1 = styled('div')({
  backgroundColor: `rgba(231, 231, 231, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.25)`,
  boxSizing: `border-box`,
  borderRadius: `40px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `301px`,
  height: `364px`,
  margin: `0px 0px 0px 16px`,
  overflow: `hidden`,
});

const Image61 = styled('img')({
  height: `225.75px`,
  width: `301px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const BestOfPragueFoodTour1 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `301px`,
  height: `56px`,
  position: `absolute`,
  left: `0px`,
  top: `226px`,
});

const Q8181Us5 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `172px`,
  height: `32px`,
  position: `absolute`,
  left: `151px`,
  top: `276px`,
});

const From5 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `52px`,
  height: `26px`,
  position: `absolute`,
  left: `12px`,
  top: `282px`,
});

const Frame75 = styled('div')({
  backgroundColor: `rgba(221, 221, 221, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `390px`,
  height: `46px`,
  left: `0px`,
  top: `261px`,
  overflow: `hidden`,
});

const Top5Activities = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Compact Display`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `167px`,
  height: `46px`,
  position: `absolute`,
  left: `12px`,
  top: `0px`,
}));

function HotelActivitiesMain(props) {
  return (
    <HotelActivitiesMain1 className={props.className}>
      <Image3 src={Image3Image} loading="lazy" alt={'image 3'} />
      <Prague>{`Prague`}</Prague>
      <SvgIcon
        component={ChevronLeftIcon}
        htmlColor={`rgba(0, 0, 0, 1)`}
      ></SvgIcon>
      <Frame3>
        <Frame4>
          <Explore>{`Explore`}</Explore>
          <Tours>{`Tours`}</Tours>
          <Tickets>{`Tickets`}</Tickets>
          <Other>{`Other`}</Other>
        </Frame4>
      </Frame3>
      <WelcomeTo>{`Welcome to`}</WelcomeTo>
      <Frame74>
        <Boat>
          <Image4 src={Image4Image} loading="lazy" alt={'image 4'} />
          <BestOfPragueBoatTour>
            {`Best of Prague - Boat Tours`}
          </BestOfPragueBoatTour>
          <Q8181Us>{`81,81 US$`}</Q8181Us>
          <From>{`From`}</From>
          <LoremIpsumDolorSitAm>
            {`Lorem ipsum dolor sit amet consectetur. Magnis vel purus non nulla quis. Ac ...`}
          </LoremIpsumDolorSitAm>
        </Boat>
        <Castle>
          <Image5 src={Image5Image} loading="lazy" alt={'image 5'} />
          <BestOfPragueCastleTo>
            {`Best of Prague - Castle Tours`}
          </BestOfPragueCastleTo>
          <Q8181Us1>{`81,81 US$`}</Q8181Us1>
          <From1>{`From`}</From1>
          <LoremIpsumDolorSitAm1>
            {`Lorem ipsum dolor sit amet consectetur. Magnis vel purus non nulla quis. Ac ...`}
          </LoremIpsumDolorSitAm1>
        </Castle>
        <Food>
          <Image6 src={Image6Image} loading="lazy" alt={'image 6'} />
          <BestOfPragueFoodTour>
            {`Best of Prague - Food Tours`}
          </BestOfPragueFoodTour>
          <Q8181Us2>{`81,81 US$`}</Q8181Us2>
          <From2>{`From`}</From2>
          <LoremIpsumDolorSitAm2>
            {`Lorem ipsum dolor sit amet consectetur. Magnis vel purus non nulla quis. Ac ...`}
          </LoremIpsumDolorSitAm2>
        </Food>
      </Frame74>
      <Frame14>
        <Boat1>
          <Image41 src={Image41Image} loading="lazy" alt={'image 4'} />
          <BestOfPragueBoatTour1>
            {`Best of Prague - Boat Tours`}
          </BestOfPragueBoatTour1>
          <Q8181Us3>{`81,81 US$`}</Q8181Us3>
          <From3>{`From`}</From3>
        </Boat1>
        <Castle1>
          <Image51 src={Image51Image} loading="lazy" alt={'image 5'} />
          <BestOfPragueCastleTo1>
            {`Best of Prague - Castle Tours`}
          </BestOfPragueCastleTo1>
          <Q8181Us4>{`81,81 US$`}</Q8181Us4>
          <From4>{`From`}</From4>
        </Castle1>
        <Food1>
          <Image61 src={Image61Image} loading="lazy" alt={'image 6'} />
          <BestOfPragueFoodTour1>
            {`Best of Prague - Food Tours`}
          </BestOfPragueFoodTour1>
          <Q8181Us5>{`81,81 US$`}</Q8181Us5>
          <From5>{`From`}</From5>
        </Food1>
      </Frame14>
      <Frame75>
        <Top5Activities>{`Top 5 activities`}</Top5Activities>
      </Frame75>
    </HotelActivitiesMain1>
  );
}

export default HotelActivitiesMain;
