/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';

const Submit1 = styled('div')({
  backgroundColor: `rgba(221, 221, 221, 1)`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `484px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const PaperplaneCircle = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `298px`,
  top: `63px`,
});

const Envelope = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro`,
  fontWeight: `400`,
  fontSize: `128px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `186px`,
  height: `169px`,
  position: `absolute`,
  left: `91px`,
  top: `112px`,
});

const TicketSentToEmail = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `269px`,
  height: `106px`,
  position: `absolute`,
  left: `44px`,
  top: `24px`,
});

const WeLookForwardToYourV = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `269px`,
  height: `169px`,
  position: `absolute`,
  left: `58px`,
  top: `285px`,
});

function Submit(props) {
  return (
    <Submit1 className={props.className}>
      <PaperplaneCircle>{`􀈡`}</PaperplaneCircle>
      <Envelope>{`􀍕`}</Envelope>
      <TicketSentToEmail>{`Ticket sent to email!`}</TicketSentToEmail>
      <WeLookForwardToYourV>
        {`We look forward to your visit!`}
      </WeLookForwardToYourV>
    </Submit1>
  );
}

export default Submit;
